# Create the image: (Run from the root git cloned folder)
# docker build -t hexdemo -f .\examples\DDOS_Hex\dockerfile .

# Run the demo:
# docker run -it hexdemo

# To Debug:
# docker run -it hexdemo /bin/bash

FROM jimhillr/julia:0.7.0

COPY . /graffsdk/GraffSDK.jl

WORKDIR /graffsdk
#RUN apt-get update
#RUN apt-get -y install git  
#RUN git clone -b 'master' --single-branch --depth 1 "https://github.com/GearsAD/GraffSDK.jl.git";

WORKDIR /graffsdk/GraffSDK.jl/examples/DDOS_Hex

RUN julia install.jl


CMD ["julia", "DDOS_Hex.jl"]